version: '3'

services:
  # Node.js Application Service
  nodejs-app:
    build: .  # Build the Docker image from the current directory
    container_name: nodejs-app  # Name the container nodejs-app
    working_dir: /usr/src/app  # Set the working directory inside the container
    command: sh -c "npm install && node index.js"  # Run npm install followed by node index.js
    ports:
      - "3000:3000"  # Map port 3000 on the host to port 3000 in the container
    environment:
      - NODE_ENV=production  # Set the environment variable NODE_ENV to production
    restart: always  # Always restart the container if it stops

  # Nginx Proxy Service
  nginx-proxy:
    image: nginx  # Use the official Nginx image
    container_name: nginx-proxy  # Name the container nginx-proxy
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  # Mount the local nginx.conf file to the container
    ports:
      - "80:80"  # Map port 80 on the host to port 80 in the container
    restart: always  # Always restart the container if it stops

  # Caddy Server Service
  caddy:
    image: caddy:latest  # Use the latest Caddy image
    container_name: caddy  # Name the container caddy
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile  # Mount the local Caddyfile to the container
      - ./public:/srv/public  # Mount the local public directory to the container
    ports:
      - "8080:8080"  # Map port 8080 on the host to port 8080 in the container
    restart: always  # Always restart the container if it stops
