version: '3'

services:
  # Node.js Application Service
  nodejs-app:
    build: .  # Build the Docker image from the current directory
    container_name: nodejs-app  
    working_dir: /usr/src/app  
    command: sh -c "npm install && node index.js"  
    ports:
      - "3000:3000"  
    environment:
      - NODE_ENV=production  
    restart: always  

  # Nginx Proxy Service
  nginx-proxy:
    image: nginx:latest
    container_name: nginx-proxy  
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  # Mount the local nginx.conf file to the container
    ports:
      - "80:80"  
    restart: always  

  # Caddy Server Service
  caddy:
    image: caddy:latest  
    container_name: caddy  
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile  # Mount the local Caddyfile to the container
      - ./public:/srv/public  # Mount the local public directory to the container
    ports:
      - "8080:8080"  
    restart: always  
