version: '3'
services:
  nodejs-app:
    build: .
    container_name: nodejs-app
    working_dir: /usr/src/app
    command: sh -c "npm install && node index.js"  # Ensures npm install runs first
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: always

  nginx-proxy:
    image: nginx
    container_name: nginx-proxy
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    restart: always

  caddy:
    image: caddy:latest
    container_name: caddy
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile  
      - ./public:/srv/public
    ports:
      - "8080:8080"  
    restart: always
