# Playbook: Set up Dockerized Application on Ubuntu 24.04
- name: Set up Dockerized Application on Ubuntu 24.04
  hosts: localhost
  become: true
  vars_files:
    - vars.yml
  tasks:
    - include_tasks: tasks/install.yml
    - include_tasks: tasks/permission.yml
    - include_tasks: tasks/run.yml

- name: Notify user to log out and log back in
  debug:
    msg: "Group membership changes have been made. Please log out and log back in to apply them."


