---
# Task: Install required packages (Docker, Docker Compose)
- name: Install required packages (Docker, Docker Compose)
  apt:
    name:
      - git  # Install Git
      - docker.io  # Install Docker
      - docker-compose  # Install Docker Compose
    state: present  # Ensure the packages are present

# Task: Add user to Docker group
- name: Add user to Docker group
  user:
    name: "{{ docker_user }}"  # Use variable for username
    group: docker  # Add the user to the Docker group

# Task: Ensure Docker is running
- name: Ensure Docker is running
  service:
    name: docker  # Specify the Docker service
    state: started  # Ensure the Docker service is started
    enabled: yes  # Ensure the Docker service is enabled to start on boot
