---
# Task: Install required packages (Docker, Docker Compose)
- name: Install required packages
  apt:
    name:
      - git
      - docker.io
      - docker-compose
    state: present
    update_cache: yes

# Task: Add user to Docker group
- name: Add user to Docker group
  user:
    name: "{{ docker_user }}"
    groups: docker
    append: yes

# Task: Ensure Docker is running
- name: Ensure Docker is running
  service:
    name: docker
    state: started
    enabled: yes

