---
# Task: Adjust ownership and permissions for deployment
- name: Set ownership for public directory
  file:
    path: "{{ playbook_dir }}/../public"
    state: directory
    owner: "{{ docker_user }}"
    group: docker
    mode: '0755'

# Task: Ensure Docker volumes are accessible by the user
- name: Adjust permissions for Docker volumes
  command: setfacl -m u:{{ docker_user }}:rwX /var/lib/docker
  become: true

