---
# Task: Build and start Docker containers using Docker Compose
- name: Build and start Docker containers
  command: docker-compose -f "../docker-compose.yml" up -d
  environment:
    DOCKER_HOST: unix:///var/run/docker.sock  # Ensure Docker socket is accessible

# Task: Verify Docker Compose version
- name: Check Docker Compose version
  shell: docker-compose --version
  register: docker_compose_version
  failed_when: docker_compose_version.rc != 0

- name: Display Docker Compose version
  debug:
    msg: "Docker Compose version: {{ docker_compose_version.stdout }}"

