---
# Task: Build and start Docker containers using Docker Compose
- name: Build and start Docker containers using Docker Compose
  command: docker-compose -f "../docker-compose.yml" up -d  # Run Docker Compose to build and start containers in detached mode

# Task: Ensure Docker Compose is installed
- name: Ensure Docker Compose is installed
  command: docker-compose --version  # Check Docker Compose version
  register: docker_compose_version  # Register the output of the command
  failed_when: docker_compose_version.rc != 0  # Fail if Docker Compose is not installed

# Task: Display Docker Compose version
- name: Display Docker Compose version
  debug:
    msg: "Docker Compose version: {{ docker_compose_version.stdout }}"  # Display the Docker Compose version
